os:
  - linux
  - osx
  - windows
dist: focal
osx_image: xcode12.5
      
language: shell
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install curl --force; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pip install --upgrade pip; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  choco install python --version=3.7; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  python -m pip install --upgrade pip ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  choco install visualstudio2019buildtools ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  choco install curl --force; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install --upgrade pip; fi
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  pip install setuptools-scm==6.0.1; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  pip install pyinstaller; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pip install pyinstaller; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  pip install pyinstaller; fi

script:
  - pyinstaller "main.spec"
  - tar -zcf "dfva_client_${TRAVIS_OS_NAME}_${TRAVIS_BUILD_NUMBER}.tar.gz" dist/
after_success:

  -  curl --ftp-create-dirs -k -T "dfva_client_${TRAVIS_OS_NAME}_${TRAVIS_BUILD_NUMBER}.tar.gz"  sftp://${visualcon_user}:${visualcon_password}@visualcon.net/home/githubdeploy/


#  - ls -R dist
#before_deploy:
#  - ls -R dist
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: "dfva_client_${TRAVIS_OS_NAME}_${TRAVIS_BUILD_NUMBER}.tar.gz"
  skip_cleanup: true
  draft: true
  on:
    tags: true

