os: osx
language: shell
osx_image: xcode12.5
before_install:
  - brew update
#  - brew install python3
  - python3 -m pip install --upgrade pip

install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install pyinstaller
script:
  - pyinstaller "main.spec"
  - ls -al dist/
before_deploy:
  - ls dist
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  draft: true
  on:
    tags: true

