os:
  - linux
  - osx
  - windows

jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode12.5
language: shell
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python --version=3.7; fi
  - python3 -m pip install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install visualstudio2019buildtools; fi
env: 
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then PATH=/c/Python37:/c/Python37/Scripts:$PATH; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install setuptools-scm==6.0.1; fi
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install pyinstaller
script:
  - pyinstaller "main.spec"
before_deploy:
  - ls dist
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  draft: true
  on:
    tags: true

