# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_fva/ui/ui_elements/requestsignature.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RequestSignature(object):
    def setupUi(self, RequestSignature):
        RequestSignature.setObjectName("RequestSignature")
        RequestSignature.resize(618, 402)
        RequestSignature.setStyleSheet("color:rgb(76, 118, 82);\n"
"background-color:rgb(216, 230, 225);")
        self.requestSignatureLayout = QtWidgets.QGridLayout(RequestSignature)
        self.requestSignatureLayout.setObjectName("requestSignatureLayout")
        self.titleLabel = QtWidgets.QLabel(RequestSignature)
        self.titleLabel.setAcceptDrops(False)
        self.titleLabel.setStyleSheet("font: bold;")
        self.titleLabel.setScaledContents(True)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.requestSignatureLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(RequestSignature)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 322))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.scrollAreaLayout.setObjectName("scrollAreaLayout")
        self.contactsFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.contactsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contactsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contactsFrame.setMidLineWidth(0)
        self.contactsFrame.setObjectName("contactsFrame")
        self.contactsFrameLayout = QtWidgets.QGridLayout(self.contactsFrame)
        self.contactsFrameLayout.setObjectName("contactsFrameLayout")
        self.search = QtWidgets.QLineEdit(self.contactsFrame)
        self.search.setStyleSheet("")
        self.search.setText("")
        self.search.setObjectName("search")
        self.contactsFrameLayout.addWidget(self.search, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.contactsFrame)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: bold;")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.contactsFrameLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.add_contact = QtWidgets.QPushButton(self.contactsFrame)
        self.add_contact.setAutoFillBackground(False)
        self.add_contact.setStyleSheet("color: rgb(11, 35, 21);\n"
"background-color: rgb(229, 229, 229);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_contact.setIcon(icon)
        self.add_contact.setObjectName("add_contact")
        self.contactsFrameLayout.addWidget(self.add_contact, 6, 1, 1, 1)
        self.contacts = QtWidgets.QTableWidget(self.contactsFrame)
        self.contacts.setObjectName("contacts")
        self.contacts.setColumnCount(0)
        self.contacts.setRowCount(0)
        self.contactsFrameLayout.addWidget(self.contacts, 4, 0, 1, 2)
        self.scrollAreaLayout.addWidget(self.contactsFrame, 0, 1, 1, 1)
        self.filesFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.filesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filesFrame.setMidLineWidth(0)
        self.filesFrame.setObjectName("filesFrame")
        self.filesFrameLayout = QtWidgets.QGridLayout(self.filesFrame)
        self.filesFrameLayout.setObjectName("filesFrameLayout")
        self.label_resumen = QtWidgets.QLabel(self.filesFrame)
        self.label_resumen.setObjectName("label_resumen")
        self.filesFrameLayout.addWidget(self.label_resumen, 5, 0, 1, 1)
        self.label_lugar = QtWidgets.QLabel(self.filesFrame)
        self.label_lugar.setObjectName("label_lugar")
        self.filesFrameLayout.addWidget(self.label_lugar, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.filesFrame)
        self.label_3.setObjectName("label_3")
        self.filesFrameLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.filesFrame)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: bold;")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.filesFrameLayout.addWidget(self.label, 3, 0, 1, 1)
        self.filesWidget = SignListWidget(self.filesFrame)
        self.filesWidget.setAcceptDrops(True)
        self.filesWidget.setObjectName("filesWidget")
        self.filesFrameLayout.addWidget(self.filesWidget, 3, 1, 1, 1)
        self.browseFiles = QtWidgets.QPushButton(self.filesFrame)
        self.browseFiles.setAutoFillBackground(False)
        self.browseFiles.setStyleSheet("color: rgb(11, 35, 21);\n"
"background-color: rgb(229, 229, 229);")
        self.browseFiles.setIcon(icon)
        self.browseFiles.setObjectName("browseFiles")
        self.filesFrameLayout.addWidget(self.browseFiles, 4, 1, 1, 1)
        self.lugar = QtWidgets.QLineEdit(self.filesFrame)
        self.lugar.setObjectName("lugar")
        self.filesFrameLayout.addWidget(self.lugar, 6, 1, 1, 1)
        self.razon = QtWidgets.QLineEdit(self.filesFrame)
        self.razon.setObjectName("razon")
        self.filesFrameLayout.addWidget(self.razon, 7, 1, 1, 1)
        self.resumen = QtWidgets.QTextEdit(self.filesFrame)
        self.resumen.setObjectName("resumen")
        self.filesFrameLayout.addWidget(self.resumen, 5, 1, 1, 1)
        self.scrollAreaLayout.addWidget(self.filesFrame, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.requestSignatureLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progress = QtWidgets.QProgressBar(RequestSignature)
        self.progress.setProperty("value", 0)
        self.progress.setOrientation(QtCore.Qt.Horizontal)
        self.progress.setInvertedAppearance(False)
        self.progress.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progress.setObjectName("progress")
        self.horizontalLayout.addWidget(self.progress)
        self.requestSignature = QtWidgets.QPushButton(RequestSignature)
        self.requestSignature.setEnabled(True)
        self.requestSignature.setSizeIncrement(QtCore.QSize(0, 0))
        self.requestSignature.setBaseSize(QtCore.QSize(0, 0))
        self.requestSignature.setStyleSheet("color: rgb(11, 35, 21);\n"
"background-color: rgb(229, 229, 229);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.requestSignature.setIcon(icon1)
        self.requestSignature.setIconSize(QtCore.QSize(16, 16))
        self.requestSignature.setObjectName("requestSignature")
        self.horizontalLayout.addWidget(self.requestSignature)
        self.requestSignatureLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)

        self.retranslateUi(RequestSignature)
        QtCore.QMetaObject.connectSlotsByName(RequestSignature)

    def retranslateUi(self, RequestSignature):
        _translate = QtCore.QCoreApplication.translate
        RequestSignature.setWindowTitle(_translate("RequestSignature", "Solicitar Firma"))
        self.titleLabel.setText(_translate("RequestSignature", "Solicitar Firma"))
        self.search.setPlaceholderText(_translate("RequestSignature", "Buscar..."))
        self.label_2.setText(_translate("RequestSignature", "Contacto"))
        self.add_contact.setText(_translate("RequestSignature", "Contacto"))
        self.label_resumen.setText(_translate("RequestSignature", "Resumen"))
        self.label_lugar.setToolTip(_translate("RequestSignature", "Solo en firmas de documentos PDF"))
        self.label_lugar.setText(_translate("RequestSignature", "Lugar *"))
        self.label_3.setToolTip(_translate("RequestSignature", "Solo en firmas de documentos PDF"))
        self.label_3.setText(_translate("RequestSignature", "Razón *"))
        self.label.setText(_translate("RequestSignature", "Archivo"))
        self.browseFiles.setText(_translate("RequestSignature", "Archivo"))
        self.progress.setFormat(_translate("RequestSignature", "Solicitando..."))
        self.requestSignature.setText(_translate("RequestSignature", "Solicitar Firma"))

from client_fva.ui.custom_components.signlistwidget import SignListWidget
from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RequestSignature = QtWidgets.QWidget()
    ui = Ui_RequestSignature()
    ui.setupUi(RequestSignature)
    RequestSignature.show()
    sys.exit(app.exec_())

