# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_elements/settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(615, 371)
        Settings.setStyleSheet("color:rgb(76, 118, 82);\n"
"background-color:rgb(216, 230, 225);")
        self.settingsLayout = QtWidgets.QVBoxLayout(Settings)
        self.settingsLayout.setObjectName("settingsLayout")
        self.titleLabel = QtWidgets.QLabel(Settings)
        self.titleLabel.setStyleSheet("font: bold;")
        self.titleLabel.setScaledContents(True)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.settingsLayout.addWidget(self.titleLabel)
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setStyleSheet("color: rgb(11, 35, 21);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.appearance = QtWidgets.QWidget()
        self.appearance.setObjectName("appearance")
        self.appearanceLayout = QtWidgets.QGridLayout(self.appearance)
        self.appearanceLayout.setObjectName("appearanceLayout")
        self.label = QtWidgets.QLabel(self.appearance)
        self.label.setStyleSheet("font: bold;\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.appearanceLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fontSize = QtWidgets.QSlider(self.appearance)
        self.fontSize.setMinimum(10)
        self.fontSize.setMaximum(25)
        self.fontSize.setSingleStep(1)
        self.fontSize.setPageStep(12)
        self.fontSize.setProperty("value", 10)
        self.fontSize.setTracking(True)
        self.fontSize.setOrientation(QtCore.Qt.Horizontal)
        self.fontSize.setInvertedAppearance(False)
        self.fontSize.setInvertedControls(True)
        self.fontSize.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.fontSize.setTickInterval(1)
        self.fontSize.setObjectName("fontSize")
        self.appearanceLayout.addWidget(self.fontSize, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.appearanceLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.appearance)
        self.label_3.setStyleSheet("font: bold;\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.appearanceLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.fontComboBox = QtWidgets.QFontComboBox(self.appearance)
        self.fontComboBox.setObjectName("fontComboBox")
        self.appearanceLayout.addWidget(self.fontComboBox, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.appearanceLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.appearance)
        self.label_2.setStyleSheet("font: bold;\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.appearanceLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.theme = QtWidgets.QComboBox(self.appearance)
        self.theme.setObjectName("theme")
        self.appearanceLayout.addWidget(self.theme, 7, 0, 1, 1)
        self.tabWidget.addTab(self.appearance, "")
        self.security = QtWidgets.QWidget()
        self.security.setObjectName("security")
        self.securityLayout = QtWidgets.QGridLayout(self.security)
        self.securityLayout.setObjectName("securityLayout")
        self.savePassword = QtWidgets.QCheckBox(self.security)
        self.savePassword.setStyleSheet("font: bold;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.savePassword.setObjectName("savePassword")
        self.securityLayout.addWidget(self.savePassword, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.securityLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.security)
        self.label_4.setStyleSheet("font: bold;\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.securityLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.security)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.securityLayout.addWidget(self.label_6, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.securityLayout.addItem(spacerItem3, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.security)
        self.label_5.setStyleSheet("font: bold;\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.securityLayout.addWidget(self.label_5, 6, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.securityLayout.addItem(spacerItem4, 8, 0, 1, 1)
        self.selectPathSaveDocs = QtWidgets.QPushButton(self.security)
        self.selectPathSaveDocs.setObjectName("selectPathSaveDocs")
        self.securityLayout.addWidget(self.selectPathSaveDocs, 8, 1, 1, 1)
        self.requestsBeforeError = QtWidgets.QSpinBox(self.security)
        self.requestsBeforeError.setProperty("value", 2)
        self.requestsBeforeError.setObjectName("requestsBeforeError")
        self.securityLayout.addWidget(self.requestsBeforeError, 3, 0, 1, 2)
        self.saveDocsPath = QtWidgets.QLineEdit(self.security)
        self.saveDocsPath.setReadOnly(True)
        self.saveDocsPath.setObjectName("saveDocsPath")
        self.securityLayout.addWidget(self.saveDocsPath, 7, 0, 1, 2)
        self.tabWidget.addTab(self.security, "")
        self.module = QtWidgets.QWidget()
        self.module.setObjectName("module")
        self.moduleLayout = QtWidgets.QGridLayout(self.module)
        self.moduleLayout.setObjectName("moduleLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.moduleLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.selectModulePath = QtWidgets.QPushButton(self.module)
        self.selectModulePath.setObjectName("selectModulePath")
        self.moduleLayout.addWidget(self.selectModulePath, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.module)
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.moduleLayout.addWidget(self.label_7, 3, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.module)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: bold;")
        self.label_8.setObjectName("label_8")
        self.moduleLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.modulePath = QtWidgets.QLineEdit(self.module)
        self.modulePath.setEnabled(True)
        self.modulePath.setFrame(True)
        self.modulePath.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.modulePath.setReadOnly(True)
        self.modulePath.setClearButtonEnabled(False)
        self.modulePath.setObjectName("modulePath")
        self.moduleLayout.addWidget(self.modulePath, 1, 0, 1, 2)
        self.label_7.raise_()
        self.selectModulePath.raise_()
        self.label_8.raise_()
        self.modulePath.raise_()
        self.tabWidget.addTab(self.module, "")
        self.settingsLayout.addWidget(self.tabWidget)
        self.buttonsWidget = QtWidgets.QWidget(Settings)
        self.buttonsWidget.setObjectName("buttonsWidget")
        self.buttonsWidgetLayout = QtWidgets.QHBoxLayout(self.buttonsWidget)
        self.buttonsWidgetLayout.setObjectName("buttonsWidgetLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsWidgetLayout.addItem(spacerItem6)
        self.apply = QtWidgets.QPushButton(self.buttonsWidget)
        self.apply.setStyleSheet("color: rgb(11, 35, 21);\n"
"background-color: rgb(229, 229, 229);")
        self.apply.setObjectName("apply")
        self.buttonsWidgetLayout.addWidget(self.apply)
        self.cancel = QtWidgets.QPushButton(self.buttonsWidget)
        self.cancel.setStyleSheet("color: rgb(11, 35, 21);\n"
"background-color: rgb(229, 229, 229);")
        self.cancel.setObjectName("cancel")
        self.buttonsWidgetLayout.addWidget(self.cancel)
        self.ok = QtWidgets.QPushButton(self.buttonsWidget)
        self.ok.setStyleSheet("color: rgb(11, 35, 21);\n"
"background-color: rgb(229, 229, 229);")
        self.ok.setObjectName("ok")
        self.buttonsWidgetLayout.addWidget(self.ok)
        self.settingsLayout.addWidget(self.buttonsWidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Preferencias"))
        self.titleLabel.setText(_translate("Settings", "Preferencias"))
        self.label.setText(_translate("Settings", "Tamaño de Letra"))
        self.label_3.setText(_translate("Settings", "Fuente"))
        self.label_2.setText(_translate("Settings", "Tema "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearance), _translate("Settings", "Apariencia"))
        self.savePassword.setText(_translate("Settings", "¿Guardar  contraseña en gestor de de contraseñas?"))
        self.label_4.setText(_translate("Settings", "Número de intentos antes de error *"))
        self.label_6.setText(_translate("Settings", "*Cuando existen problemas de red"))
        self.label_5.setText(_translate("Settings", "Guardar documentos firmados en"))
        self.selectPathSaveDocs.setText(_translate("Settings", "..."))
        self.requestsBeforeError.setSuffix(_translate("Settings", " intentos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.security), _translate("Settings", "Seguridad"))
        self.selectModulePath.setText(_translate("Settings", "..."))
        self.label_7.setText(_translate("Settings", "* Corresponde al lugar en la máquina dónde se ubica el módulo para el dispositivo de firma (PKCS11)"))
        self.label_8.setText(_translate("Settings", "Ubicación del Módulo *"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.module), _translate("Settings", "Módulo"))
        self.apply.setText(_translate("Settings", "Aplicar"))
        self.cancel.setText(_translate("Settings", "Cancelar"))
        self.ok.setText(_translate("Settings", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

