# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_fva/ui/ui_elements/tabdefault.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabDefault(object):
    def setupUi(self, TabDefault):
        TabDefault.setObjectName("TabDefault")
        TabDefault.resize(615, 371)
        TabDefault.setStyleSheet("color:rgb(76, 118, 82);\n"
"background-color:rgb(216, 230, 225);")
        self.tabDefaultLayout = QtWidgets.QGridLayout(TabDefault)
        self.tabDefaultLayout.setObjectName("tabDefaultLayout")
        self.initialMessageLbl = QtWidgets.QLabel(TabDefault)
        self.initialMessageLbl.setStyleSheet("font: bold;")
        self.initialMessageLbl.setScaledContents(True)
        self.initialMessageLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.initialMessageLbl.setWordWrap(True)
        self.initialMessageLbl.setObjectName("initialMessageLbl")
        self.tabDefaultLayout.addWidget(self.initialMessageLbl, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 139, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tabDefaultLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tabDefaultLayout.addItem(spacerItem1, 2, 0, 1, 1)

        self.retranslateUi(TabDefault)
        QtCore.QMetaObject.connectSlotsByName(TabDefault)

    def retranslateUi(self, TabDefault):
        _translate = QtCore.QCoreApplication.translate
        TabDefault.setWindowTitle(_translate("TabDefault", "Sin Dispositivo"))
        self.initialMessageLbl.setText(_translate("TabDefault", "Favor conecte su dispositivo de firma para comenzar."))
from . import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabDefault = QtWidgets.QWidget()
    ui = Ui_TabDefault()
    ui.setupUi(TabDefault)
    TabDefault.show()
    sys.exit(app.exec_())
